#!/usr/bin/env php
<?php
echo "Started " . microtime(true) . "\n";
while(true) {
    sleep(5);
    $stderr = fopen('php://stderr', 'w');
    fwrite($stderr,"stderr Tick " . microtime(true) . "\n");
    fclose($stderr);
    echo "Tick " . microtime(true) . "\n";
}