#!/usr/bin/env php
<?php
/**
 * Shortlived CLI application
 */
echo "Started " . microtime(true) . "\n";

$stderr = fopen('php://stderr', 'w');
fwrite($stderr,"stderr Tick " . microtime(true) . "\n");
fclose($stderr);

sleep(5);

echo "Stopped " . microtime(true) . "\n";